In [1]:
import pandas as pd
import numpy as np

In [2]:
Crime_df = pd.read_csv('C:\\Users\\vamsh\\Documents\\Uni\\UChicago\\Autumn 2022\\MSCA 31012_IP02 - Data Engineering Platforms for Analytics\\Project\\Data\\Crimes_2022.csv', encoding = 'gbk', header = 0)

In [3]:
Crime_df.head(5)

,ID,Case Number,Date,Block,IUCR,Primary Type,Description,Location Description,Arrest,Domestic,...,Ward,Community Area,FBI Code,X Coordinate,Y Coordinate,Year,Updated On,Latitude,Longitude,Location
0,12767443,JF325104,06/30/2022 08:00:00 AM,046XX N DOVER ST,0890,THEFT,FROM BUILDING,APARTMENT,False,False,...,46.0,3,06,1165858.0,1930868.0,2022,10/25/2022 04:46:49 PM,41.965890,-87.665555,"(41.965890278, -87.665555028)"
1,12768376,JF326399,07/20/2022 12:40:00 PM,029XX W 25TH ST,0486,BATTERY,DOMESTIC BATTERY SIMPLE,SIDEWALK,False,True,...,12.0,30,08B,1156917.0,1887255.0,2022,10/25/2022 04:46:49 PM,41.846399,-87.699614,"(41.84639902, -87.699614045)"
2,12764940,JF322387,07/18/2022 05:00:00 PM,004XX E 89TH ST,0910,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,...,9.0,44,07,1180638.0,1846066.0,2022,10/25/2022 04:46:49 PM,41.732859,-87.613825,"(41.73285929, -87.613824932)"
3,12770333,JF328642,07/23/2022 01:59:00 PM,045XX N FRANCISCO AVE,0810,THEFT,OVER $500,STREET,False,False,...,33.0,14,06,1156230.0,1929931.0,2022,10/25/2022 04:46:49 PM,41.963520,-87.700981,"(41.963519549, -87.70098077)"
4,12766636,JF324240,07/20/2022 04:10:00 AM,055XX S PRAIRIE AVE,0486,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,...,20.0,40,08B,1178988.0,1868183.0,2022,10/25/2022 04:46:49 PM,41.793588,-87.619197,"(41.793588428, -87.619196923)"

In [5]:
# Dropping rows with Nulls
Crime_df.dropna(axis = 0, how = 'any',inplace = True)

In [6]:
Crime_df.isnull().sum()

ID                      0
Case Number             0
Date                    0
Block                   0
IUCR                    0
Primary Type            0
Description             0
Location Description    0
Arrest                  0
Domestic                0
Beat                    0
District                0
Ward                    0
Community Area          0
FBI Code                0
X Coordinate            0
Y Coordinate            0
Year                    0
Updated On              0
Latitude                0
Longitude               0
Location                0
dtype: int64

In [7]:
# Dropping Unnecessary columns
Crime_df.drop(['IUCR', 'Beat', 'Ward', 'FBI Code', 'X Coordinate', 'Y Coordinate', 'Year', 'Updated On'], axis = 1, inplace = True)

In [8]:
Crime_df.shape

(192996, 14)

In [9]:
# Renaming ID column and changing all column headers to upper case for consistency
Crime_df.rename(columns={"ID":"CrimeID"}, inplace = True)
Crime_df.columns = Crime_df.columns.str.upper()
Crime_df.head(5)

,CRIMEID,CASE NUMBER,DATE,BLOCK,PRIMARY TYPE,DESCRIPTION,LOCATION DESCRIPTION,ARREST,DOMESTIC,DISTRICT,COMMUNITY AREA,LATITUDE,LONGITUDE,LOCATION
0,12767443,JF325104,06/30/2022 08:00:00 AM,046XX N DOVER ST,THEFT,FROM BUILDING,APARTMENT,False,False,19,3,41.965890,-87.665555,"(41.965890278, -87.665555028)"
1,12768376,JF326399,07/20/2022 12:40:00 PM,029XX W 25TH ST,BATTERY,DOMESTIC BATTERY SIMPLE,SIDEWALK,False,True,10,30,41.846399,-87.699614,"(41.84639902, -87.699614045)"
2,12764940,JF322387,07/18/2022 05:00:00 PM,004XX E 89TH ST,MOTOR VEHICLE THEFT,AUTOMOBILE,STREET,False,False,6,44,41.732859,-87.613825,"(41.73285929, -87.613824932)"
3,12770333,JF328642,07/23/2022 01:59:00 PM,045XX N FRANCISCO AVE,THEFT,OVER $500,STREET,False,False,17,14,41.963520,-87.700981,"(41.963519549, -87.70098077)"
4,12766636,JF324240,07/20/2022 04:10:00 AM,055XX S PRAIRIE AVE,BATTERY,DOMESTIC BATTERY SIMPLE,APARTMENT,False,True,2,40,41.793588,-87.619197,"(41.793588428, -87.619196923)"

In [11]:
Crime_df.to_csv('C:\\Users\\vamsh\\Documents\\Uni\\UChicago\\Autumn 2022\\MSCA 31012_IP02 - Data Engineering Platforms for Analytics\\Project\\Data\\Crimes_Circa_2022_final1.csv', encoding='utf-8', index=False)